site_name: OCRganizer
site_description: AI-powered PDF document organization and categorization system
site_url: https://yourusername.github.io/OCRganizer
repo_url: https://github.com/yourusername/OCRganizer
repo_name: yourusername/OCRganizer

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mermaid2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: docs/quick-start.md
    - Installation: docs/installation.md
    - User Guide: docs/user-guide.md
    - CLI Usage: docs/cli-usage.md
  - AI Providers:
    - AI Provider Setup: docs/ai-provider-setup.md
    - Configuration Reference: docs/configuration.md
    - LM Studio Setup: docs/lm-studio-setup.md
  - Development:
    - Developer Guide: docs/developer-guide.md
    - API Reference: docs/api.md
    - Improvements: docs/improvements.md
  - Support:
    - Troubleshooting: docs/troubleshooting.md

plugins:
  - search
  - mermaid2
