site_name: OCRganizer
site_description: AI-powered PDF document organization and categorization system
site_url: https://jeffredodd.github.io/OCRganizer
repo_url: https://github.com/jeffredodd/OCRganizer
repo_name: jeffredodd/OCRganizer

docs_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Installation: installation.md
    - User Guide: user-guide.md
    - CLI Usage: cli-usage.md
  - AI Providers:
    - AI Provider Setup: ai-provider-setup.md
    - Configuration Reference: configuration.md
    - LM Studio Setup: lm-studio-setup.md
  - Development:
    - Developer Guide: developer-guide.md
    - API Reference: api.md
  - Support:
    - Troubleshooting: troubleshooting.md

plugins:
  - search
  - mermaid2
