name: Deploy Documentation to Wiki

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Wiki
      run: |
        # Clone the wiki repository
        git clone https://github.com/jeffredodd/OCRganizer.wiki.git wiki
        cd wiki
        
        # Clear existing markdown files
        rm -f *.md
        
        # Copy markdown files from docs directory
        cp ../docs/*.md .
        
        # Create Home.md from index.md if it exists
        if [ -f ../docs/index.md ]; then
          cp ../docs/index.md Home.md
        fi
        
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Add and commit changes
        git add .
        git commit -m "Update wiki documentation from main branch" || exit 0
        
        # Push to wiki
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jeffredodd/OCRganizer.wiki.git
